[package]
name = "downrest/typedevent"
version = "1.0.4"
description = "A typed remote event wrapper, taking advantage of function types (...) -> () for typechecking parameters with names on both firing and listening."
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
exclude = [
    "rokit.toml",
    "README.md"
]

[dependencies]
